-- Active: 1720600689142@@127.0.0.1@3306
# 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS `stock` CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

# goBatch 사용을 위한 테이블 생성
CREATE TABLE IF NOT EXISTS stock.batch_job_instance
(
    JOB_INSTANCE_ID BIGINT       NOT NULL AUTO_INCREMENT,
    JOB_NAME        VARCHAR(100) NOT NULL,
    JOB_KEY         VARCHAR(32)  NOT NULL,
    JOB_PARAMS      VARCHAR(512) NOT NULL,
    CREATE_TIME     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (JOB_INSTANCE_ID),
    UNIQUE UNIQ_JOB_INST(JOB_NAME, JOB_KEY)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS stock.batch_job_execution
(
    JOB_EXECUTION_ID BIGINT        NOT NULL AUTO_INCREMENT,
    VERSION          BIGINT        NOT NULL DEFAULT 0,
    JOB_INSTANCE_ID  BIGINT        NOT NULL,
    JOB_NAME         VARCHAR(100)  NOT NULL,
    CREATE_TIME      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    START_TIME       DATETIME      NOT NULL DEFAULT '0000-00-00 00:00:00',
    END_TIME         DATETIME      NOT NULL DEFAULT '0000-00-00 00:00:00',
    STATUS           VARCHAR(10)   NOT NULL,
    EXIT_CODE        VARCHAR(2500) NOT NULL DEFAULT '',
    EXIT_MESSAGE     VARCHAR(10000),
    LAST_UPDATED     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (JOB_EXECUTION_ID)
) ENGINE=InnoDB;

set sql_mode='ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS stock.batch_job_context
(
    JOB_CONTEXT_ID  BIGINT       NOT NULL AUTO_INCREMENT,
    JOB_INSTANCE_ID BIGINT       NOT NULL,
    JOB_NAME        VARCHAR(100) NOT NULL,
    JOB_CONTEXT     LONGTEXT,
    CREATE_TIME     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (JOB_CONTEXT_ID),
    UNIQUE UNIQ_JOB_INST(JOB_INSTANCE_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS stock.batch_step_execution
(
    STEP_EXECUTION_ID  BIGINT        NOT NULL AUTO_INCREMENT,
    VERSION            BIGINT        NOT NULL DEFAULT 0,
    JOB_NAME           VARCHAR(100)  NOT NULL,
    JOB_INSTANCE_ID    BIGINT        NOT NULL,
    JOB_EXECUTION_ID   BIGINT        NOT NULL,
    STEP_NAME          VARCHAR(100)  NOT NULL,
    CREATE_TIME        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    START_TIME         DATETIME      NOT NULL DEFAULT '0000-00-00 00:00:00',
    END_TIME           DATETIME      NOT NULL DEFAULT '0000-00-00 00:00:00',
    STATUS             VARCHAR(10)   NOT NULL,
    COMMIT_COUNT       BIGINT,
    READ_COUNT         BIGINT,
    FILTER_COUNT       BIGINT,
    WRITE_COUNT        BIGINT,
    READ_SKIP_COUNT    BIGINT,
    WRITE_SKIP_COUNT   BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT     BIGINT,
    EXECUTION_CONTEXT  VARCHAR(2000) NOT NULL,
    STEP_CONTEXT_ID    BIGINT        NOT NULL,
    EXIT_CODE          VARCHAR(2500) NOT NULL DEFAULT '',
    EXIT_MESSAGE       VARCHAR(10000),
    LAST_UPDATED       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (STEP_EXECUTION_ID),
    KEY                IDX_JOB_EXECUTION_ID(JOB_EXECUTION_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS stock.batch_step_context
(
    STEP_CONTEXT_ID BIGINT       NOT NULL AUTO_INCREMENT,
    JOB_INSTANCE_ID BIGINT       NOT NULL,
    STEP_NAME       VARCHAR(100) NOT NULL,
    STEP_CONTEXT    LONGTEXT,
    CREATE_TIME     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (STEP_CONTEXT_ID),
    UNIQUE UNIQ_JOB_INST_STEP(JOB_INSTANCE_ID, STEP_NAME)
) ENGINE=InnoDB;