# 데이터베이스 삭제
# DROP DATABASE IF EXISTS `STOCK`;

DROP TABLE IF EXISTS STOCK.BATCH_JOB_INSTANCE;
DROP TABLE IF EXISTS STOCK.BATCH_JOB_EXECUTION;
DROP TABLE IF EXISTS STOCK.BATCH_JOB_CONTEXT;
DROP TABLE IF EXISTS STOCK.BATCH_JOB_CONTEXT;
DROP TABLE IF EXISTS STOCK.BATCH_STEP_CONTEXT;